### PR TITLE
Fix for "NI1017 gives false positives involving array initializers"

### LINKED ISSUE #46: NI1017 gives false positives involving array initializers.
The code below reports a failure of rule NI1017 but it shouldn't. Removing the Max at the end avoids the error but it is on its own line so it shouldn't be a problem.

private static int MaxCounts(IEnumerable<int> numbers)
{
    var max = new[]
        {
            numbers.Count(number => number == 1),
            numbers.Count(number => number == 2),
            numbers.Count(number => number == 3)
        }
        .Max();
    return max;
}

### PR DESCRIPTION
**Pull request by tsharma-ni**
# Justification
#46

# Implementation
Array initializers can have individual invocation expressions separated by commas instead of ".". Tweaked the logic of the analyzer to handle array initializers separately - only looking at direct child nodes of an array initializer and handling individual invocation expressions within the array initializer.

# Testing
- Existing tests pass.
- New tests pass.

### CODE REVIEW

**Comment by Everest2020** [comment]
What about the jagged arrays?

**Comment by tsharma-ni** [comment]
> What about the jagged arrays?

@Everest2020 should be the same syntax - `SyntaxKind.ArrayInitializerExpression`. Do you have a test case in mind?

**Comment by Everest2020** [comment]
> > What about the jagged arrays?
> 
> @Everest2020 should be the same syntax - `SyntaxKind.ArrayInitializerExpression`. Do you have a test case in mind?

How about this test case?

```csharp
        private static int Test(IEnumerable<int> numbers)
        {
            var temp = new int[][]
            {
                new [] {
                numbers.Count(number => number == 1),
                numbers.Count(number => number == 2),
                numbers.Count(number => number == 3)
                },

                new [] {
                numbers.Count(number => number == 1),
                numbers.Count(number => number == 2),
                numbers.Count(number => number == 3)},

                new [] {
                numbers.Count(number => number == 1),
                numbers.Count(number => number == 2),
                numbers.Count(number => number == 3)},

            };
            return 42;
        }
```

**Comment by tsharma-ni** [comment]
> > > What about the jagged arrays?
> > 
> > 
> > @Everest2020 should be the same syntax - `SyntaxKind.ArrayInitializerExpression`. Do you have a test case in mind?
> 
> How about this test case?
> 
> ```cs
>         private static int Test(IEnumerable<int> numbers)
>         {
>             var temp = new int[][]
>             {
>                 new [] {
>                 numbers.Count(number => number == 1),
>                 numbers.Count(number => number == 2),
>                 numbers.Count(number => number == 3)
>                 },
> 
>                 new [] {
>                 numbers.Count(number => number == 1),
>                 numbers.Count(number => number == 2),
>                 numbers.Count(number => number == 3)},
> 
>                 new [] {
>                 numbers.Count(number => number == 1),
>                 numbers.Count(number => number == 2),
>                 numbers.Count(number => number == 3)},
> 
>             };
>             return 42;
>         }
> ```

I added a test for this. Thanks @Everest2020!

**Review by jryckman — APPROVED** [review]
I am deferring this to @pakdev  because he's more familiar with analyzer code.

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 1]
```diff
@@ -36,25 +36,52 @@ public override void Initialize(AnalysisContext context)
...
                 SyntaxKind.Argument,
                 SyntaxKind.ArrowExpressionClause);
+
+            context.RegisterSyntaxNodeAction(
+                AnalyzeArrayInitializerContext,
+                SyntaxKind.ArrayInitializerExpression);
         }
 
-        private static void AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
+        private static void AnalyzeSyntaxContext(SyntaxNodeAnalysisContext context)
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: `AnalyzeSyntaxContext` is generic and really an "action" that accepts a "context" as its parameter. I'd rename it to something like `AnalyzeExpression` or something more fitting for its `SyntaxKind`s. Same with `AnalyzeArrayInitializerContext`

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 2]
```diff
@@ -36,25 +36,52 @@ public override void Initialize(AnalysisContext context)
...
             // or a chain of them
             var invocationExpressionSyntax = parentSyntaxNode
-                .DescendantNodes()
+                .DescendantNodes(IsNotArrayCreationSyntax)
                 .OfType<InvocationExpressionSyntax>()
                 .FirstOrDefault();
 
+            AnalyzeSyntaxNode(invocationExpressionSyntax, context.ReportDiagnostic);
+
+            bool IsNotArrayCreationSyntax(SyntaxNode syntaxNode) => !syntaxNode.IsKind(SyntaxKind.ArrayCreationExpression);
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs:64]: Do we have to do this check for the `SyntaxKind`s we selected?

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 3]
```diff
@@ -36,25 +36,52 @@ public override void Initialize(AnalysisContext context)
...
+                .OfType<InvocationExpressionSyntax>();
+
+            // Analyze individual invocation expressions
+            foreach (var invocationExpression in invocationExpressions)
+            {
+                AnalyzeSyntaxNode(invocationExpression, context.ReportDiagnostic);
+            }
+        }
+
+        private static void AnalyzeSyntaxNode(InvocationExpressionSyntax invocationExpressionSyntax, Action<Diagnostic> reportDiagnostic)
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Name this something less generic

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 4]
```diff
@@ -36,25 +36,52 @@ public override void Initialize(AnalysisContext context)
...
                 .FirstOrDefault();
 
+            AnalyzeSyntaxNode(invocationExpressionSyntax, context.ReportDiagnostic);
+
+            bool IsNotArrayCreationSyntax(SyntaxNode syntaxNode) => !syntaxNode.IsKind(SyntaxKind.ArrayCreationExpression);
+        }
+
+        private static void AnalyzeArrayInitializerContext(SyntaxNodeAnalysisContext context)
+        {
+            var arrayInitializerSyntaxNode = context.Node;
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Drop the "node" suffix (the other analyzers don't call them nodes)

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 5]
```diff
@@ -36,25 +36,52 @@ public override void Initialize(AnalysisContext context)
...
+
+            // Find only direct child invocation expressions
+            var invocationExpressions = arrayInitializerSyntaxNode
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: `invocationExpressionSyntaxes`. My convention is to suffix anything that's syntax with "Syntax" so if I get the symbol I can just call it the same thing w/o "Syntax"

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 6]
```diff
@@ -98,14 +125,18 @@ private static void AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
...
                     var diagnostic = Diagnostic.Create(Rule, invocationExpressionSyntax.GetLocation());
-                    context.ReportDiagnostic(diagnostic);
+                    reportDiagnostic(diagnostic);
                     break;
                 }
             }
 
             bool IsLambdaExpression(SyntaxNode syntaxNode) => syntaxNode.IsKind(SyntaxKind.SimpleLambdaExpression);
 
+            bool IsNonNested(SyntaxNode syntaxNode) => IsNotArgumentSyntax(syntaxNode) && IsNotArrayInitializerSyntax(syntaxNode);
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: I don't know what "non-nested" means based on this definition. Is there another name more descriptive (ideally positive vs. negative)?

File: tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs [hunk 7]
```diff
@@ -642,6 +642,289 @@ private interface ISoftwareContent
...
+
+namespace NationalInstruments.Analyzers.UnitTests
+{
+    class Test
+    {
+        private static int MaxCounts(IEnumerable<int> numbers, ISoftwareContent softwareContent)
+        {
+            var max = new[]
+            {
+                <|>softwareContent.Children(x => false).Count(s => s.AliasName == ""U""),
```
Comment (pakdev) [inline tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs:692]: Are we sure we don't want one-liners in array initializers?

File: tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs [hunk 8]
```diff
@@ -642,6 +642,289 @@ private interface ISoftwareContent
...
+        }
+    }
+}
+",
+GetNI1017Rule(),
+GetNI1017Rule());
+
+            VerifyDiagnostics(test);
+        }
+
```
Comment (pakdev) [inline tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs:927]: What about a lambda that creates an array with lambas?

**Review by pakdev — DISMISSED** [review]
Pretty minor comments - thanks for fixing this issue!

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 1 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Fixed [here](https://github.com/ni/csharp-styleguide/pull/65/commits/d2079a7f6644f6a39faa54aa6fa294d8552725c9).

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 3 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: How about [this](https://github.com/ni/csharp-styleguide/pull/65/commits/6d602757ba6eaca7afa6c713e5275c3aa57a3766)?

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 4 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Fixed [here](https://github.com/ni/csharp-styleguide/pull/65/commits/f0828a0e8908b2cfaac4199c0551a709ecdeb0df).

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 5 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Fixed [here](https://github.com/ni/csharp-styleguide/pull/65/commits/d6f8e929e94e3ba597336ec3a1a1108980eecd1d).

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 6 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: How about [this](https://github.com/ni/csharp-styleguide/pull/65/commits/96736965f3e7d9fa4377598ba4740bf24350ef64)?

File: tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs (hunk 7 above)
Comment (tsharma-ni) [reply tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs:692]: I think so. @jryckman?

File: tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs (hunk 8 above)
Comment (tsharma-ni) [reply tests/NationalInstruments.Analyzers.UnitTests/ChainOfMethodsWithLambdasAnalyzerTests.cs:927]: Thanks for pointing this out! Added test case [here](https://github.com/ni/csharp-styleguide/pull/65/commits/a8c67bafec7f0a615a8cee3a99a3cf4029e4f072).

**Comment by tsharma-ni** [comment]
@pakdev thanks for the quick review! 

I have tried my best, but naming is hard, so bear with me.😄

**Comment by tsharma-ni** [comment]
Hi @pakdev, any more feedback?

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 9]
```diff
@@ -36,25 +36,53 @@ public override void Initialize(AnalysisContext context)
...
+        {
+            var arrayInitializerSyntax = context.Node;
+
+            // Find only direct child invocation expressions
+            var invocationExpressionSyntaxes = arrayInitializerSyntax
+                .ChildNodes()
+                .OfType<InvocationExpressionSyntax>();
+
+            // Analyze individual invocation expressions
+            foreach (var invocationExpression in invocationExpressionSyntaxes)
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: `invocationExpression` is a `SyntaxNode`, so I'd suffix it with "Syntax"

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs [hunk 10]
```diff
@@ -36,25 +36,53 @@ public override void Initialize(AnalysisContext context)
...
             // or a chain of them
             var invocationExpressionSyntax = parentSyntaxNode
-                .DescendantNodes()
+                .DescendantNodes(IsNotArrayInitializerSyntax)
                 .OfType<InvocationExpressionSyntax>()
                 .FirstOrDefault();
 
+            AnalyzeInvocationExpression(invocationExpressionSyntax, context.ReportDiagnostic);
+
+            bool IsNotArrayInitializerSyntax(SyntaxNode syntaxNode) =>
```
Comment (pakdev) [inline src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: This is duplicated on line 140; make into a static method

**Review by pakdev — DISMISSED** [review]
Just correct those last couple of things and you're good to go!

**Comment by pakdev** [comment]
> Hi @pakdev, any more feedback?

Sorry it took me so long - GitHub was notifying my personal email account vs. my work one. Apparently you can configure email notification per organization, though, so now my responses should be timely.

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 9 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Fixed [here](https://github.com/ni/csharp-styleguide/pull/65/commits/f8436c60098422a579a4049a0f9b835d1bea260a).

File: src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs (hunk 10 above)
Comment (tsharma-ni) [reply src/NationalInstruments.Analyzers/Style/ChainOfMethodsWithLambdasAnalyzer.cs]: Fixed [here](https://github.com/ni/csharp-styleguide/pull/65/commits/ddf7d01411a02d42c5cd752cf2aecc9fee28ed70).

**Review by pakdev — APPROVED** [review]
